#!/usr/bin/env python3
"""Export the built-in themes from ``ui.theme`` to ``resources/themes/``.

Keeps the QSS files in sync with the single source of truth:
    .venv/bin/python scripts/export_themes.py
"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from devworkbench.ui.theme import LIGHT, DARK, _render  # noqa: E402

OUT = ROOT / "resources" / "themes"


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, tokens in (("dark", DARK), ("light", LIGHT)):
        target = OUT / f"{name}.qss"
        target.write_text(
            f"/* Generated by scripts/export_themes.py — edit ui/theme.py instead. */\n"
            f"{_render(tokens)}",
            encoding="utf-8",
        )
        print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
